name: gta_6_comapnion_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+14

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.3.0
  slide_countdown: ^2.0.1
  google_mobile_ads: ^8.0.0
  photo_view: ^0.15.0
  shared_preferences: 2.5.5

  # Firebase
  firebase_core: 4.13.0
  firebase_messaging: 16.5.0
  cloud_firestore: 6.8.0
  firebase_analytics: 12.4.6
  firebase_auth: 6.5.7

  # Other packages
  url_launcher: ^6.3.2
  http: ^1.2.2
  youtube_player_flutter: ^10.0.1
  video_player: ^2.10.0
  cupertino_icons: ^1.0.8
  in_app_purchase: ^3.3.1
  supabase_flutter: 2.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/explore/
    - assets/avatars/
