// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwNn-FweCxS1bqW5CgGnjoHEovtsNGDgM',
    appId: '1:283463782171:web:363e53c8a6e05121298dbe',
    messagingSenderId: '283463782171',
    projectId: 'gta6-companion-app',
    authDomain: 'gta6-companion-app.firebaseapp.com',
    storageBucket: 'gta6-companion-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAPOnZwRzGJygZrN-eRWOx0EjIJsCI3rM',
    appId: '1:283463782171:android:23245deb25f9271f298dbe',
    messagingSenderId: '283463782171',
    projectId: 'gta6-companion-app',
    storageBucket: 'gta6-companion-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiibb3xL28s6F6raSZuzPDzEVAZjruYao',
    appId: '1:283463782171:ios:c8b7b24a5046b810298dbe',
    messagingSenderId: '283463782171',
    projectId: 'gta6-companion-app',
    storageBucket: 'gta6-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.gta6ComapnionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiibb3xL28s6F6raSZuzPDzEVAZjruYao',
    appId: '1:283463782171:ios:c8b7b24a5046b810298dbe',
    messagingSenderId: '283463782171',
    projectId: 'gta6-companion-app',
    storageBucket: 'gta6-companion-app.firebasestorage.app',
    iosBundleId: 'com.example.gta6ComapnionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwNn-FweCxS1bqW5CgGnjoHEovtsNGDgM',
    appId: '1:283463782171:web:5db2d58eac382222298dbe',
    messagingSenderId: '283463782171',
    projectId: 'gta6-companion-app',
    authDomain: 'gta6-companion-app.firebaseapp.com',
    storageBucket: 'gta6-companion-app.firebasestorage.app',
  );
}
